spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/itemservice-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

# My Batis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE